name: "Build"
on:
  workflow_dispatch:
  pull_request:
  push:
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - name: Install direnv
        run: |
          curl -sfL https://direnv.net/install.sh | bash
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Load environment variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"
      - name: Build
        run: |
          make build CMAKE_CXX_CLANG_TIDY=clang-tidy
      - name: Upload build folder artifact
        uses: actions/upload-artifact@v6
        with:
          name: build
          path: build
          retention-days: 1
      - name: Upload bin artifact
        uses: actions/upload-artifact@v6
        with:
          name: bin
          path: build/bin
  build-no-nix:
    name: Build with no Nix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install deps
        run: |
          sudo apt install cmake \
            clang \
            git \
            ninja-build
      - name: Build
        run: |
          make build CMAKE_CXX_CLANG_TIDY=clang-tidy
  build-nix:
    name: Build with Nix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - name: Install direnv
        run: |
          curl -sfL https://direnv.net/install.sh | bash
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Load environment variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"
      - name: Build
        run: |
          nix build
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - name: Install direnv
        run: |
          curl -sfL https://direnv.net/install.sh | bash
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Load environment variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"
      - uses: actions/download-artifact@v5
        with:
          name: build
          path: build
      - name: Test
        run: |
          make test
  test-no-nix:
    name: Test with no Nix
    runs-on: ubuntu-latest
    needs: build-no-nix
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install deps
        run: |
          sudo apt install cmake \
            clang \
            git \
            ninja-build
      - uses: actions/download-artifact@v5
        with:
          name: build
          path: build
      - name: Test
        run: |
          make test
